# Generated by Django 5.2.1 on 2025-10-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0004_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="mobile_number",
            new_name="email",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
