# Generated by Django 5.2.3 on 2025-06-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='blogs/')),
                ('content', models.TextField()),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('category', models.CharField(default='Travel', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
