# Generated by Django 5.2.3 on 2025-06-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
