# Generated by Django 5.2.1 on 2025-06-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
